### ISSUE TITLE
Grade data and total students

### ISSUE THREAD

**Issue by drwang22** [cougargrades/web#136]
Add a column in the chart with total students enrolled in a section. Also is there an update on the 2022 fall data?

**Comment by au5ton** [comment]
This seems like a good feature to add. I'm still waiting for the university to send me back Fall 2022 data.

**Comment by au5ton** [comment]
This feature has been implemented and will be in CougarGrades 1.1.0

**Comment by au5ton** [comment]
This feature is now live on cougargrades.io 🎉
