### ISSUE TITLE
COSC 6372 appears to have a data type mismatch

### ISSUE THREAD

**Issue by rickdgray** [cougargrades/web#32]
https://cougargrades.io/c/COSC%206372

The data here does not get populated correctly.

**Comment by au5ton** [comment]
Thanks for reporting this @rickdgray ! 

The error in the console looks like:

```
Error: Invalid type, object, for column "A".
```

I think this is an issue where if a course has a `null` for any of its sections' grade data (missing data from UH), then the graphing fails.

Here is what the database looks like for that section: 
![image](https://user-images.githubusercontent.com/4109551/103817412-4321be00-502c-11eb-8f23-b83b51a842e1.png)

**Comment by au5ton** [comment]
related to #7

**Comment by au5ton** [comment]
This fix has been deployed to production in version 0.4.4. Thank you @rickdgray ! 😊
